# Azure DevOps pipeline template used to build bundle.
  
steps:
- bash: |
    echo 'IO_PAY_PORTAL_API_HOST: $IO_PAY_PORTAL_API_HOST'
    echo 'IO_PAY_PORTAL_API_REQUEST_TIMEOUT: $IO_PAY_PORTAL_API_REQUEST_TIMEOUT'
    chmod +x env.sh && source env.sh
    yarn build
  workingDirectory: io-pay-portal-fe
  env:
    IO_PAY_PORTAL_API_HOST: $(IO_PAY_PORTAL_API_HOST)
    IO_PAY_PORTAL_API_REQUEST_TIMEOUT: $(IO_PAY_PORTAL_API_REQUEST_TIMEOUT)
  displayName: 'Build files'
  