# Azure DevOps pipeline template used to build bundle.
  
steps:
- bash: |
    echo 'IO_PAY_PORTAL_API_HOST: $IO_PAY_PORTAL_API_HOST'
    echo 'IO_PAY_PORTAL_API_REQUEST_TIMEOUT: $IO_PAY_PORTAL_API_REQUEST_TIMEOUT'
    echo 'IO_PAY_PORTAL_PAY_WL_HOST: $IO_PAY_PORTAL_PAY_WL_HOST'
    echo 'IO_PAY_PORTAL_PAY_WL_POLLING_INTERVAL: $IO_PAY_PORTAL_PAY_WL_POLLING_INTERVAL'
    echo 'IO_PAY_PORTAL_PAY_WL_POLLING_ATTEMPTS: $IO_PAY_PORTAL_PAY_WL_POLLING_ATTEMPTS'
    chmod +x env.sh && source env.sh
    yarn build
  workingDirectory: io-pay-portal-fe
  env:
    IO_PAY_PORTAL_API_HOST: $(IO_PAY_PORTAL_API_HOST)
    IO_PAY_PORTAL_API_REQUEST_TIMEOUT: $(IO_PAY_PORTAL_API_REQUEST_TIMEOUT)
    IO_PAY_PORTAL_PAY_WL_HOST: $(IO_PAY_PORTAL_PAY_WL_HOST)
    IO_PAY_PORTAL_PAY_WL_POLLING_INTERVAL: $(IO_PAY_PORTAL_PAY_WL_POLLING_INTERVAL)
    IO_PAY_PORTAL_PAY_WL_POLLING_ATTEMPTS: $(IO_PAY_PORTAL_PAY_WL_POLLING_ATTEMPTS)
  displayName: 'Build files'
  