name: "Deploy"

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  RESOURCE_GROUP_NAME: news-p-weu-core-app-rg
  APP_NAME: news-p-weu-core-app-fn

jobs:
  runner_job:
    name: Runner Job
    runs-on: ubuntu-22.04
    environment: prod-cd #### use your specific identity!
    steps:

      - name: Checkout
        id: checkout
        # from https://github.com/actions/checkout/commits/main
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 #v4.1.7
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version-file: "app/.node-version"

      - name: 'Install and build'
        run: |
          cd app
          yarn install --immutable
          yarn predeploy

      - name: Login
        id: login
        # from https://github.com/Azure/login/commits/master
        uses: azure/login@6c251865b4e6290e7b78be643ea2d005bc51f69a #v2.1.1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy
        uses: azure/webapps-deploy@2fdd5c3ebb4e540834e86ecc1f6fdcd5539023ee #v3.0.2
        with:
          resource-group-name: ${{ env.RESOURCE_GROUP_NAME }}
          app-name: ${{ env.APP_NAME }}
          package: app
